version: '3'
services:
    db:
        image: postgres:9.6.4-alpine
    api:
        image: python:3.6.2
        container_name: api
        volumes:
            - ./api:/api
        working_dir: /api
        command: /bin/sh -c "cd /api && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - db
        expose:
            - "8000"
    ngninx:
        image: nginx:1.13.3-alpine
        ports:
            - "8000:8000"
        volumes:
            - ./api:/api
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - api
    frontend:
        image: node:8.4.0-alpine
        container_name: frontend
        ports:
            - "4200:4200"
        volumes:
            - ./frontend:/frontend
        working_dir: /frontend
        command: /bin/sh -c "cd /frontend && npm install && ./node_modules/.bin/ng serve --host=0.0.0.0"
        depends_on:
            - api
